version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      nodejs: 8
      python: 3.7
    commands:
       - pip install --upgrade pip
       - pip install --upgrade awscli
       - pip install pytest pytest-cov
       - npm install -g serverless
       - sls plugin install -n serverless-python-requirements
       - sls plugin install -n serverless-prune-plugin
  pre_build:
    commands:
       - pytest -v --cov=src
  build:
    commands:
       - sls deploy --verbose --config $SERVERLESS_YML_PATH
